name: Dockerhub Build

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: harbor.jenkins-x-viettel.iviet.com
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:dockerhub"
          platforms: linux/amd64
          tags: koslib/ga-helm-eks:latest, koslib/ga-helm-eks:${{ github.event.inputs.tag }}
